version: "3.9"
services:

  mongo:
    image: ${IMAGES_MONGO}
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/mongo:/data/db

  postgis:
    image: ${IMAGES_POSTGIS}
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/postgis/data:/var/lib/postgresql/data

  pims-cache:
    image: ${IMAGES_PIMS_CACHE}
    restart: unless-stopped

  pims:
    image: ${IMAGES_PIMS}
    restart: unless-stopped
    depends_on:
      - nginx
      - pims-cache
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/images:${CONTAINER_PATHS_IMAGES}

  core:
    image: ${IMAGES_CORE}
    restart: unless-stopped
    depends_on:
      - nginx
      - postgis
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime

  web_ui:
    image: ${IMAGES_WEB_UI}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime

  nginx:
    image: ${IMAGES_NGINX}
    restart: unless-stopped
    ports:
      - 80:80

  app-engine:
    image: ${IMAGES_APPENGINE}
    restart: unless-stopped

  registry:
    image: ${IMAGES_REGISTRY}
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/registry:/data