version: "3.9"
services:

  mongo:
    image: $IMAGE_MONGO
    name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db 

  postgis:
    image: $IMAGE_POSTGIS
    name: postgis
    restart: unless-stopped
    volumes:
      - postgis_data:/var/lib/postgresql
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 8G

  rabbitmq:
    image: $IMAGE_RABBITMQ
    name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672
      - 15672

  bioformat:
    image: $IMAGE_BIOFORMAT
    name: bioformat
    restart: unless-stopped
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES
    
  pims: 
    image: $IMAGE_PIMS
    name: pims
    restart: unless-stopped
    depends_on:
      - pims-cache
      - rabbitmq
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED  # why subpath of /data/images rather than another path ???
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          cpus: '4'
          memory: 4G
    
  core:
    image: $IMAGE_CORE
    name: core
    restart: unless-stopped
    depends_on:
      - postgis
      - mongo
      - rabbitmq
    volumes:
      - $HOST_PATHS_JAVAMELODY:$JAVAMELODY_PATH
      - /etc/localtime:/etc/localtime

  web_ui:
    image: $IMAGE_WEBUI
    name: web_ui
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime

  nginx:
    image: $IMAGE_NGINX
    name: nginx
    restart: unless_stopped
    depends_on:
      - pims
      - core
      - web_ui
    ports:
      - 80
    volumes:
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED
    
volumes:
  - mongo_data
  - postgis_data
